src/Entity/Equip.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EquipRepository")
 */
class Equip
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $categoria;

    /**
     * @ORM\Column(type="integer")
     */
    private $divisio;

    /**
     * @ORM\Column(type="date")
     */
    private $any_fundacio;

    /**
     * @ORM\Column(type="integer")
     */
    private $partits_jugats;

    /**
     * @ORM\Column(type="integer")
     */
    private $partits_guanyats;

    /**
     * @ORM\Column(type="integer")
     */
    private $partits_empatats;

    /**
     * @ORM\Column(type="integer")
     */
    private $partits_perduts;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCategoria(): ?string
    {
        return $this->categoria;
    }

    public function setCategoria(string $categoria): self
    {
        $this->categoria = $categoria;

        return $this;
    }

    public function getDivisio(): ?int
    {
        return $this->divisio;
    }

    public function setDivisio(int $divisio): self
    {
        $this->divisio = $divisio;

        return $this;
    }

    public function getAnyFundacio(): ?\DateTimeInterface
    {
        return $this->any_fundacio;
    }

    public function setAnyFundacio(\DateTimeInterface $any_fundacio): self
    {
        $this->any_fundacio = $any_fundacio;

        return $this;
    }

    public function getPartitsJugats(): ?int
    {
        return $this->partits_jugats;
    }

    public function setPartitsJugats(int $partits_jugats): self
    {
        $this->partits_jugats = $partits_jugats;

        return $this;
    }

    public function getPartitsGuanyats(): ?int
    {
        return $this->partits_guanyats;
    }

    public function setPartitsGuanyats(int $partits_guanyats): self
    {
        $this->partits_guanyats = $partits_guanyats;

        return $this;
    }

    public function getPartitsEmpatats(): ?int
    {
        return $this->partits_empatats;
    }

    public function setPartitsEmpatats(int $partits_empatats): self
    {
        $this->partits_empatats = $partits_empatats;

        return $this;
    }

    public function getPartitsPerduts(): ?int
    {
        return $this->partits_perduts;
    }

    public function setPartitsPerduts(int $partits_perduts): self
    {
        $this->partits_perduts = $partits_perduts;

        return $this;
    }

    //x
  /**
   * @ORM\ManyToMany(targetEntity="Entrenador", mappedBy="equips")
   */
  private $entrenadors;

  public function __construct()
  {
    $this->entrenadors = new ArrayCollection();
  }

  public function addEntrenador(Entrenador $entrenador)
  {
    if (!$this->entrenadors->contains($entrenador)) {
      $this->entrenadors[] = $entrenador;
      $entrenador->addEquip($this);
    }

    return $this;
  }

  public function removeEntrenador(Entrenador $entrenador)
  {
    if ($this->entrenadors->contains($entrenador)) {
      $this->entrenadors->removeElement($entrenador);
      $entrenador->removeEquip($this);
    }
  }

  public function getEntrenadors()
  {
    return $this->entrenadors;
  }

  public function __toString()
  {
    return $this->nom;
  }

}

src/Form/EquipType.php
<?php

namespace App\Form;

use App\Entity\Equip;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EquipType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('categoria')
            ->add('divisio')
            ->add('any_fundacio')
            ->add('partits_jugats')
            ->add('partits_guanyats')
            ->add('partits_empatats')
            ->add('partits_perduts')
            ->add('entrenadors')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Equip::class,
        ]);
    }
}

src/Controller/EquipController.php
<?php

namespace App\Controller;

use App\Entity\Equip;
use App\Form\EquipType;
use App\Repository\EquipRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/equip")
 */
class EquipController extends AbstractController
{
    /**
     * @Route("/", name="equip_index", methods={"GET"})
     */
    public function index(EquipRepository $equipRepository): Response
    {
        return $this->render('equip/index.html.twig', [
            'equips' => $equipRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="equip_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $equip = new Equip();
        $form = $this->createForm(EquipType::class, $equip);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($equip);
            $entityManager->flush();

            return $this->redirectToRoute('equip_index');
        }

        return $this->render('equip/new.html.twig', [
            'equip' => $equip,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="equip_show", methods={"GET"})
     */
    public function show(Equip $equip): Response
    {
        return $this->render('equip/show.html.twig', [
            'equip' => $equip,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="equip_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Equip $equip): Response
    {
        $form = $this->createForm(EquipType::class, $equip);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('equip_index');
        }

        return $this->render('equip/edit.html.twig', [
            'equip' => $equip,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="equip_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Equip $equip): Response
    {
        if ($this->isCsrfTokenValid('delete'.$equip->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($equip);
            $entityManager->flush();
        }

        return $this->redirectToRoute('equip_index');
    }
}

templates/equip/_delete_form.html.twig
<form method="post" action="{{ path('equip_delete', {'id': equip.id}) }}" onsubmit="return confirm('Esteu segur que voleu suprimir aquest element?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ equip.id) }}">
    <button class="btn">Eliminar</button>
</form>

templates/equip/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <span>Recorda per seleccionar més d'un equip o entrenador, manten pulsat CTRL i selecciona els que vulguis.</span>
    <br/>
    <button class="btn">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}

templates/equip/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Equip{% endblock %}

{% block body %}
    <h1>Edita Equip</h1>

    {{ include('equip/_form.html.twig', {'button_label': 'Actualitza'}) }}

    <a href="{{ path('equip_index') }}">Torna a la llista</a>

    {{ include('equip/_delete_form.html.twig') }}
{% endblock %}

templates/equip/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Equip index{% endblock %}

{% block body %}
    <h1>Equip - <a href="/">Home</a></h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Categoria</th>
                <th>Divisio</th>
                <th>Any Fundacio</th>
                <th>Partits Jugats</th>
                <th>Partits Guanyats</th>
                <th>Partits Empatats</th>
                <th>Partits Perduts</th>
                <th>Accions</th>
            </tr>
        </thead>
        <tbody>
        {% for equip in equips %}
            <tr>
                <td>{{ equip.id }}</td>
                <td>{{ equip.nom }}</td>
                <td>{{ equip.categoria }}</td>
                <td>{{ equip.divisio }}</td>
                <td>{{ equip.anyFundacio ? equip.anyFundacio|date('Y-m-d') : '' }}</td>
                <td>{{ equip.partitsJugats }}</td>
                <td>{{ equip.partitsGuanyats }}</td>
                <td>{{ equip.partitsEmpatats }}</td>
                <td>{{ equip.partitsPerduts }}</td>
                <td>
                    <a href="{{ path('equip_show', {'id': equip.id}) }}">Mostra</a>
                    <a href="{{ path('equip_edit', {'id': equip.id}) }}">Edita</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">Llista buida</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('equip_new') }}">Crea un nou Equip</a>
{% endblock %}

templates/equip/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Equip{% endblock %}

{% block body %}
    <h1>Crea un nou Equip</h1>

    {{ include('equip/_form.html.twig') }}

    <a href="{{ path('equip_index') }}">Torna a la llista</a>
{% endblock %}

templates/equip/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Equip{% endblock %}

{% block body %}
    <h1>Equip</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ equip.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ equip.nom }}</td>
            </tr>
            <tr>
                <th>Categoria</th>
                <td>{{ equip.categoria }}</td>
            </tr>
            <tr>
                <th>Divisio</th>
                <td>{{ equip.divisio }}</td>
            </tr>
            <tr>
                <th>Any Fundacio</th>
                <td>{{ equip.anyFundacio ? equip.anyFundacio|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Partits Jugats</th>
                <td>{{ equip.partitsJugats }}</td>
            </tr>
            <tr>
                <th>Partits Guanyats</th>
                <td>{{ equip.partitsGuanyats }}</td>
            </tr>
            <tr>
                <th>Partits Empatats</th>
                <td>{{ equip.partitsEmpatats }}</td>
            </tr>
            <tr>
                <th>Partits Perduts</th>
                <td>{{ equip.partitsPerduts }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('equip_index') }}">Torna a la llista</a>

    <a href="{{ path('equip_edit', {'id': equip.id}) }}">Edita</a>

    {{ include('equip/_delete_form.html.twig') }}
{% endblock %}