src/Entity/Entrenador.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EntrenadorRepository")
 */
class Entrenador
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $cognom;

    /**
     * @ORM\Column(type="boolean")
     */
    private $primer_entrenador;

    /**
     * @ORM\Column(type="integer")
     */
    private $edat;

    /**
     * @ORM\Column(type="integer")
     */
    private $partits_jugats;

    /**
     * @ORM\Column(type="integer")
     */
    private $partits_guanyats;

    /**
     * @ORM\Column(type="integer")
     */
    private $partits_empatats;

    /**
     * @ORM\Column(type="integer")
     */
    private $partits_perduts;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCognom(): ?string
    {
        return $this->cognom;
    }

    public function setCognom(string $cognom): self
    {
        $this->cognom = $cognom;

        return $this;
    }

    public function getPrimerEntrenador(): ?bool
    {
        return $this->primer_entrenador;
    }

    public function setPrimerEntrenador(bool $primer_entrenador): self
    {
        $this->primer_entrenador = $primer_entrenador;

        return $this;
    }

    public function getEdat(): ?int
    {
        return $this->edat;
    }

    public function setEdat(int $edat): self
    {
        $this->edat = $edat;

        return $this;
    }

    public function getPartitsJugats(): ?int
    {
        return $this->partits_jugats;
    }

    public function setPartitsJugats(int $partits_jugats): self
    {
        $this->partits_jugats = $partits_jugats;

        return $this;
    }

    public function getPartitsGuanyats(): ?int
    {
        return $this->partits_guanyats;
    }

    public function setPartitsGuanyats(int $partits_guanyats): self
    {
        $this->partits_guanyats = $partits_guanyats;

        return $this;
    }

    public function getPartitsEmpatats(): ?int
    {
        return $this->partits_empatats;
    }

    public function setPartitsEmpatats(int $partits_empatats): self
    {
        $this->partits_empatats = $partits_empatats;

        return $this;
    }

    public function getPartitsPerduts(): ?int
    {
        return $this->partits_perduts;
    }

    public function setPartitsPerduts(int $partits_perduts): self
    {
        $this->partits_perduts = $partits_perduts;

        return $this;
    }

    //x
    /**
     * @ORM\ManyToMany(targetEntity="Equip", inversedBy="entrenadors")
     * @ORM\JoinTable(
     *     name="equips_entrenadors",
     *     joinColumns={
     *          @ORM\JoinColumn(name="entrenadors_id", referencedColumnName="id")
     *     },
     *     inverseJoinColumns={
     *          @ORM\JoinColumn(name="equips_id", referencedColumnName="id")
     *     }
     * )
     */
    private $equips;

    public function __construct()
    {
      $this->equips = new ArrayCollection();
    }

  public function addEquip(Equip $equip)
  {
    if (!$this->equips->contains($equip)) {
      $this->equips[] = $equip;
      $equip->addEntrenador($this);
    }

    return $this;
  }

  public function removeEquip(Equip $equip)
  {
    if ($this->equips->contains($equip)) {
      $this->equips->removeElement($equip);
      $equip->removeEntrenador($this);
    }
  }

  public function getEquips()
  {
    return $this->equips;
  }

  public function __toString()
  {
    return $this->nom;
  }
}

src/Form/EntrenadorType.php
<?php

namespace App\Form;

use App\Entity\Entrenador;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EntrenadorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('cognom')
            ->add('primer_entrenador')
            ->add('edat')
            ->add('partits_jugats')
            ->add('partits_guanyats')
            ->add('partits_empatats')
            ->add('partits_perduts')
            ->add('equips')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Entrenador::class,
        ]);
    }
}

src/Controller/EntrenadorController.php
<?php

namespace App\Controller;

use App\Entity\Entrenador;
use App\Form\EntrenadorType;
use App\Repository\EntrenadorRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/entrenador")
 */
class EntrenadorController extends AbstractController
{
    /**
     * @Route("/", name="entrenador_index", methods={"GET"})
     */
    public function index(EntrenadorRepository $entrenadorRepository): Response
    {
        return $this->render('entrenador/index.html.twig', [
            'entrenadors' => $entrenadorRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="entrenador_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $entrenador = new Entrenador();
        $form = $this->createForm(EntrenadorType::class, $entrenador);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($entrenador);
            $entityManager->flush();

            return $this->redirectToRoute('entrenador_index');
        }

        return $this->render('entrenador/new.html.twig', [
            'entrenador' => $entrenador,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="entrenador_show", methods={"GET"})
     */
    public function show(Entrenador $entrenador): Response
    {
        return $this->render('entrenador/show.html.twig', [
            'entrenador' => $entrenador,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="entrenador_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Entrenador $entrenador): Response
    {
        $form = $this->createForm(EntrenadorType::class, $entrenador);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('entrenador_index');
        }

        return $this->render('entrenador/edit.html.twig', [
            'entrenador' => $entrenador,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="entrenador_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Entrenador $entrenador): Response
    {
        if ($this->isCsrfTokenValid('delete'.$entrenador->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($entrenador);
            $entityManager->flush();
        }

        return $this->redirectToRoute('entrenador_index');
    }
}

templates/entrenador/_delete_form.html.twig
<form method="post" action="{{ path('entrenador_delete', {'id': entrenador.id}) }}" onsubmit="return confirm('Esteu segur que voleu suprimir aquest element?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ entrenador.id) }}">
    <button class="btn">Eliminar</button>
</form>

templates/entrenador/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <span>Recorda per seleccionar més d'un equip o entrenador, manten pulsat CTRL i selecciona els que vulguis.</span>
    <br/>
    <button class="btn">{{ button_label|default('Guarda') }}</button>
{{ form_end(form) }}

templates/entrenador/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Entrenador{% endblock %}

{% block body %}
    <h1>Edita Entrenador</h1>

    {{ include('entrenador/_form.html.twig', {'button_label': 'Actualitza'}) }}

    <a href="{{ path('entrenador_index') }}">Torna a la llista</a>

    {{ include('entrenador/_delete_form.html.twig') }}
{% endblock %}

templates/entrenador/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Entrenador index{% endblock %}

{% block body %}
    <h1>Entrenador - <a href="/">Home</a></h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Cognom</th>
                <th>Primer Entrenador</th>
                <th>Edat</th>
                <th>Partits jugats</th>
                <th>Partits Guanyats</th>
                <th>Partits Empatats</th>
                <th>Partits Perduts</th>
                <th>Accions</th>
            </tr>
        </thead>
        <tbody>
        {% for entrenador in entrenadors %}
            <tr>
                <td>{{ entrenador.id }}</td>
                <td>{{ entrenador.nom }}</td>
                <td>{{ entrenador.cognom }}</td>
                <td>{{ entrenador.primerEntrenador ? 'Yes' : 'No' }}</td>
                <td>{{ entrenador.edat }}</td>
                <td>{{ entrenador.partitsJugats }}</td>
                <td>{{ entrenador.partitsGuanyats }}</td>
                <td>{{ entrenador.partitsEmpatats }}</td>
                <td>{{ entrenador.partitsPerduts }}</td>
                <td>
                    <a href="{{ path('entrenador_show', {'id': entrenador.id}) }}">Mostara</a>
                    <a href="{{ path('entrenador_edit', {'id': entrenador.id}) }}">Edita</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">Llista buida</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('entrenador_new') }}">Crea un nou Entrenador</a>
{% endblock %}

templates/entrenador/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Entrenador{% endblock %}

{% block body %}
    <h1>Crea un nou Entrenador</h1>

    {{ include('entrenador/_form.html.twig') }}

    <a href="{{ path('entrenador_index') }}">Torna a la llista</a>
{% endblock %}

templates/entrenador/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Entrenador{% endblock %}

{% block body %}
    <h1>Entrenador</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ entrenador.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ entrenador.nom }}</td>
            </tr>
            <tr>
                <th>Cognom</th>
                <td>{{ entrenador.cognom }}</td>
            </tr>
            <tr>
                <th>Primer Entrenador</th>
                <td>{{ entrenador.primerEntrenador ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Edat</th>
                <td>{{ entrenador.edat }}</td>
            </tr>
            <tr>
                <th>Partits Jugats</th>
                <td>{{ entrenador.partitsJugats }}</td>
            </tr>
            <tr>
                <th>Partits Guanyats</th>
                <td>{{ entrenador.partitsGuanyats }}</td>
            </tr>
            <tr>
                <th>Partits Empatats</th>
                <td>{{ entrenador.partitsEmpatats }}</td>
            </tr>
            <tr>
                <th>Partits Perduts</th>
                <td>{{ entrenador.partitsPerduts }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('entrenador_index') }}">Torna a la llista</a>

    <a href="{{ path('entrenador_edit', {'id': entrenador.id}) }}">Edita</a>

    {{ include('entrenador/_delete_form.html.twig') }}
{% endblock %}